# GenieACS v1.2 Dockerfile #
############################

FROM node:current-buster-slim

#RUN npm install -g --unsafe-perm genieacs@1.2.0
WORKDIR /opt/genieacs
COPY ./src /opt/genieacs/src
COPY ./package.json /opt/genieacs/package.json
COPY ./tsconfig.json /opt/genieacs/tsconfig.json
RUN npm install
RUN npm run build-tsc
RUN rm -rf ./src



#RUN mkdir /opt/genieacs
#RUN mkdir /opt/genieacs/ext
#RUN chown genieacs:genieacs /opt/genieacs/ext

#RUN mkdir /var/log/genieacs
#RUN chown genieacs:genieacs /var/log/genieacs

#ADD genieacs.logrotate /etc/logrotate.d/genieacs

#WORKDIR /opt
#RUN git clone https://github.com/DrumSergio/genieacs-services -b 1.2
#RUN cp genieacs-services/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#RUN cp genieacs-services/run_with_env.sh /usr/bin/run_with_env.sh
#RUN chmod +x /usr/bin/run_with_env.sh

#WORKDIR /var/log/genieacs

#CMD ["/usr/bin/supervisord","-c","/etc/supervisor/conf.d/supervisord.conf"]